### ISSUE TITLE
Unable to find xrf file

### ISSUE THREAD

**Issue by shangshi66** [Kuree/hgdb-vitis#3] opened 2022-10-19 16:10 UTC
Hi!

I was trying to run hgdb-vitis on a simple design to see if I have installed it right. But I got this issue that I cannot solve:

AssertionError: Unable to find file solution1/.debug/top_Pipeline_VITIS_LOOP_12_1.xrf
![image](https://user-images.githubusercontent.com/42651957/196746146-6cce750f-fe76-4885-b65c-2b02e5f0136c.png)

Would you please help me with this?

**Comment by Kuree** [comment] 2022-10-19 18:01
Did you turn the debug flag on in Vitis?

**Comment by shangshi66** [comment] 2022-10-19 20:01
Thank you for quick respond!
Do you mean config_debug? I tried to, but in the GUI of Vitis it would let me change the value of config_debug, so I had to run vitis in interactive mode in terminal to use command to change the value of config_debug and than open the solution, but I still get the same error.
![image](https://user-images.githubusercontent.com/42651957/196792144-a0d94aaf-1bde-4b44-882e-a2c8b1637c47.png)

**Comment by Kuree** [comment] 2022-10-19 22:02
You should use `config_debug -enable` in your setup script and then run the entire HLS flow, i.e. C-simulation and synthesis, then you should find the xrf file.

**Comment by shangshi66** [comment] 2022-10-20 17:37
I have tried it. But I still get that error. Here is my tcl script. Am I doing it right?
![image](https://user-images.githubusercontent.com/42651957/197019420-c715dcd2-bf89-4882-8075-44bfbb57fd60.png)

**Comment by Kuree** [comment] 2022-10-20 18:15
Hmm I'm not sure manually editing tcl script would work, since Vitis overrides that file quite often. Here is what I did:

![image](https://user-images.githubusercontent.com/6099149/197026402-d7d43bb9-39a5-424c-b180-df266bd3f94b.png)

Then if you run C SYNTHESIS, you will see the files in the debug folder:
```
$ ls .debug/*.xrf
.debug/convolve_Pipeline_VITIS_LOOP_6_1.xrf  .debug/convolve.xrf
```

**Comment by shangshi66** [comment] 2022-10-20 18:46
Oh yeah it worked! But I'm running into some other error
![image](https://user-images.githubusercontent.com/42651957/197032148-2d00b06c-69b1-44e2-a9d2-bd980ef0fa34.png)

**Comment by Kuree** [comment] 2022-10-21 00:14
Make sure you also run the C-simulation. I think these bitcode files are created from the C sim.

**Comment by shangshi66** [comment] 2022-10-21 02:09
Yeah I did run the C-simulation. Am I using the proper config?
![image](https://user-images.githubusercontent.com/42651957/197094785-205455ae-f408-4c32-a88a-3919b57a95ec.png)

**Comment by Kuree** [comment] 2022-10-21 02:43
That looks correct. Do you have a function called `top` by any chance? It could be that the heuristics I used may not pick up the design hierarchy properly. If it is possible, can you share your design file here?

**Comment by shangshi66** [comment] 2022-10-21 17:11
Sure! I'm just trying to run it on a very simple prime check design. The top function is called top. But I have tried to change it to something else and it still doesn't work. It seems the .c file is not allowed to be posted here, I'll just put an image.
![image](https://user-images.githubusercontent.com/42651957/197250510-d5e5ba1b-8f9d-48d7-bbef-9f030d7bb390.png)

**Comment by Kuree** [comment] 2022-10-30 20:08
Sorry for the delay. I'm swamped by the workload I have right now. I will definitely get back to you once I have more free time.

**Comment by shangshi66** [comment] 2022-11-01 03:03
Yeah, sure!

**Comment by NathanRizza** [comment] 2022-11-03 00:06
Hello, my name is Nathan and Shang has passed this project onto me. 

I think I have figured out the most recent issue of not finding the debug bitcode. When I searched the .autopilot/db/ directory for the bc file I found a few different ones but one in particular named "PC.bc". I think that this means hgdb-vitis is looking for a bitcode based off the function name (top.bc) but vitis is writing it based off the filename (PC.bc). I changed the file and function names to match and I believe that I have progressed further into the program but let me know if my conclusion is wrong and that's an unrelated file. 


Since then I have run into a different issue as shown in my screenshot. It says that it is unable to determine the location for my file pc.c but it has given the exact path for the file so I'm not sure what it is unable to find. 

Thanks for your help thus far by the way.
![Screenshot_20221102_192146](https://user-images.githubusercontent.com/56983564/199624713-99979987-c3c4-413b-91bd-78cda68148d5.png)

**Comment by Kuree** [comment] 2022-11-03 01:41
@NathanRizza Thanks for the info. I think you're right that Vitis generates the bitcode object by filename, not the function name. During my tests I always keep them the same so I never noticed it. I will figure out a way to detect filename automatically.

From the error message it seems like it has obtained all the debugging information but failed to produce a valid symbol table. Here is code section that's throwing the error: https://github.com/Kuree/hgdb-vitis/blob/5b15700a6e008c243dd00910c3f69693c4b0fe2c/python/ir.cc#L987

Is it possible to zip up your solution folder and upload it somewhere? You can see some example file structure [here](https://github.com/Kuree/files/tree/master/vectors/hls). Basically it needs `syn`, `.autopilot`, and `.debug` folder.

I should have more free time this week and I will take a look. Hopefully it's an easy fix.

**Comment by NathanRizza** [comment] 2022-11-06 20:03
@Kuree I have uploaded the soluition folder to this link: "https://mega.nz/file/tfI3kIzI#lrHHJH4AuX1jJguGmC8KyufPfozjIOCxikeK6DSozUI". Thanks for taking a look at it.

**Comment by Kuree** [comment] 2022-11-10 01:22
@NathanRizza I am able to reproduce this bug. When I ran `hgdb-vitis`, LLVM i actually complaining the invalid debug info:
```
DILocation not allowed within this metadata node
!13 = !{!"fpga.top", !"user", !14}
!14 = !DILocation(line: 1, column: 16, scope: !7)
```
This means that the bitcode is produced using a much older compiler. What version of Vitis are you using? I'm using 2021.1 and it seems to produce fairly recent bitcode files.

I've successfully opened the bitcode file with much older llvm, e.g. llvm-7. I will keep experimenting.

**Comment by NathanRizza** [comment] 2022-11-10 03:42
@Kuree I am using vitis version 2022.2. Also I am running ubuntu 22.04 LTS. When Checking the version of llvm I am running I get this "llvm is already the newest version (1:14.0-55~exp2)" so I think you're observations are correct. Is this an issue that can be fixed for the newer version of llvm or should I downgrade to llvm-7?

**Comment by Kuree** [comment] 2022-11-10 04:13
I don't think you need to downgrade. I just need to find a way to set up the code such that it should dynamically detect the Vitis version and choose the correct LLVM to build against (and download if not exist). I will keep you posted.

**Comment by Kuree** [comment] 2022-11-11 22:15
Should be fixed in the master branch. Feel free to reopen or create a new issue if it doesn't work for you. I was able to create a symbol table given your solution files.

**Closed** 2022-11-11 22:14 UTC
